In [10]:
from sqlalchemy import (
    Boolean,
    Column,
    Float,
    Integer,
    MetaData,
    String,
    Table,
    text,
    update,
)

from egomimic.utils.aws.aws_sql import (
    TableRow,
    create_default_engine,
    episode_table_to_df,
)

In [11]:
engine = create_default_engine()

Tables in schema 'app': ['episodes']

In [12]:
df = episode_table_to_df(engine)
df

,episode_hash,operator,task,embodiment,robot_name,num_frames,task_description,scene,objects,zarr_processed_path,zarr_mp4_path,zarr_processing_error,is_deleted,data_type
0,69c2e11d8d047e12c1437b49,696a41576adfd3c664a4884d,wrapping_bouquets,mecka,mecka_bimanual,3599,A person is meticulously assembling a decorati...,design_station,"[""rose_bouquet"", ""wrapping_paper"", ""tape"", ""sc...",/vol/zarr_output/69c2e11d8d047e12c1437b49.zarr,,,False,flagship
1,692ba7636f03b95efa014e19,691fb9aabe785d95f3c92975,sorting_coffee_beans,mecka,mecka_bimanual,2701,The person is sorting coffee beans on a wooden...,coffee_processing_area,"[""coffee_beans"", ""wooden_tray"", ""bowl"", ""stool""]",/vol/egoverse-zarr-data/692ba7636f03b95efa014e...,/vol/egoverse-zarr-data/692ba7636f03b95efa014e...,,False,flagship
2,69c2e11ed5c62ba7c4d5abd0,696875ceb5a168dd96784e60,portioning_dough,mecka,mecka_bimanual,3595,A person uses a tool to cut green dough into s...,production_area,"[""dough"", ""scale"", ""baking_tray""]",/vol/zarr_output/69c2e11ed5c62ba7c4d5abd0.zarr,,,False,flagship
3,693ceb7686fa42a6428d031d,6939a1c4c67c9e4814b02dbd,packaging_products,mecka,mecka_bimanual,2701,The person is sorting and inspecting various f...,stockroom,"[""face_masks"", ""plastic_bags"", ""cardboard_box""]",/vol/egoverse-zarr-data/693ceb7686fa42a6428d03...,/vol/egoverse-zarr-data/693ceb7686fa42a6428d03...,,False,flagship
4,69c2e120f2e7c4de1485053b,696722f683a9fdf2d86f263b,grinding_coffee_beans,mecka,mecka_bimanual,3599,The person is preparing a manual coffee grinde...,counter,"[""coffee_beans"", ""ground_coffee"", ""coffee_bags...",/vol/zarr_output/69c2e120f2e7c4de1485053b.zarr,,,False,flagship
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200095,69c43971286a122e71af6145,6969246e567cdf8c8737861a,peeling_garlic,mecka,mecka_bimanual,2095,A person is manually peeling garlic bulbs by h...,produce_section,"[""garlic"", ""mesh_bags"", ""garlic_skins""]",/vol/zarr_output/69c43971286a122e71af6145.zarr,,,False,flagship
200096,69c4397268912ffee1187965,696ef6184766dbef4c55d59c,ironing_clothes,mecka,mecka_bimanual,2095,The person is ironing and folding a black garm...,stockroom,"[""t_shirt"", ""ironing_pad"", ""folded_clothes""]",/vol/zarr_output/69c4397268912ffee1187965.zarr,,,False,flagship
200097,69c43974354a8e82ba8b68f3,69462b145f30bef91a6668e4,cutting_meat,mecka,mecka_bimanual,2065,A person is slicing a large piece of meat into...,kitchen,"[""raw_meat"", ""bowl"", ""cutting_board""]",/vol/zarr_output/69c43974354a8e82ba8b68f3.zarr,,,False,flagship
200098,69c4397d75aab850dc99dc8d,6981e6b9f8ca4464d98d2f77,kneading_dough,mecka,mecka_bimanual,2056,prepare green dough by mixing liquid ingredien...,production_area,"[""dough"", ""bowl"", ""liquid_container"", ""flour_b...",/vol/zarr_output/69c4397d75aab850dc99dc8d.zarr,,,False,flagship
200099,69c4398020e5477dc5e7c333,69738b3189fa4bc311d05ec4,labeling_pastries,mecka,mecka_bimanual,1945,The person is going through a tray of plastic-...,production_area,"[""pastries"", ""labels"", ""tray"", ""plastic_bags"",...",/vol/zarr_output/69c4398020e5477dc5e7c333.zarr,,,False,flagship

In [16]:
# Filter to certain lab
print("Unique tasks:", set(df["task"]))
print("Number of unique tasks:", df["task"].nunique())
tasks_with_more_than_5 = df["task"].value_counts()[df["task"].value_counts() > 5].index.tolist()
print("Tasks with more than 5 elements:", tasks_with_more_than_5)

Unique tasks: {'writing_notes', 'shaving_chocolate', 'operating_gluing_machine', 'arranging_bills', 'gluing_booklets', 'constructing_bases', 'washing_cooker_pots', 'clearing_laser_cutter', 'crafting_flowers', 'drying_cups', 'assembling_circuit_boards', 'washing_refrigerator_shelves', 'labeling_jars', 'drying_glassware', 'preparing_shoes', 'adjusting_cables', 'folding_invitations', 'washing_metal_rings', 'peeling_wrappers', 'preparing_coffee_drinks', 'making_truffles', 'cleaning_cloths', 'collecting_manure', 'frying_pastes', 'arranging_mugs', 'hammering_metal_pieces', 'assembling_covers', 'separating_dough_circles', 'painting_bamboo', 'tying_wood_planks', 'preparing_carrots', 'painting_cakes', 'scrubbing_poles', 'arranging_stones', 'forming_wire_shapes', 'frying_chips', 'starting_mixers', 'preparing_nursery_bags', 'knotting_fabrics', 'repairing_electrical_plugs', 'screwing_speaker_panels', 'assembling_keyboards', 'mincing_food', 'chopping_chicken', 'reassembling_tvs', 'sewing_garment_components', 'replacing_screens', 'grafting_vines', 'packing_containers', 'screwing_heatsinks', 'filling_seed_bags', 'attaching_guides', 'trimming_planks', 'beading_accessories', 'skewering_fabrics', 'cooking_omelets', 'wrapping_fan_handles', 'cooking_noodles', 'weaving_wire', 'winding_motor_coils', 'sanding_tiles', 'arranging_greenery', 'cleaning_pipe_fittings', 'cutting_grapes', 'rolling_stuffed_cabbages', 'removing_metal_shields', 'peeling_cassava', 'applying_wood_fillers', 'raking_debris', 'sorting_electrical_terminals', 'leatherworking', 'preparing_petals', 'securing_bouquet_wraps', 'shaping_metal_wire', 'scraping_phone_frames', 'layering_flower_petals', 'assembling_electrical_panels', 'diamond_painting', 'flattening_plastic_sheets', 'kneading_ingredients', 'managing_customer_orders', 'arranging_letters', 'assembling_wood_parts', 'separating_bread_rolls', 'washing_coffee_equipment', 'packaging_food_granules', 'adding_food_coloring', 'cleaning_heating_elements', 'cutting_and_gluing_foam', 'folding_and_bagging_fabrics', 'rolling_and_cutting_dough', 'cleaning_notebooks', 'portioning_food', 'lidding_containers', 'tidying', 'drilling_blocks', 'stapling_wrappers', 'dismantling_boards', 'labeling_books', 'weaving_plastic_wrappers', 'scraping_coconuts', 'cutting_rubber_tubes', 'cooking_fritters', 'decorating_straws', 'misting_vegetables', 'cutting_chicken_legs', 'cutting_pizza_dough', 'restocking_candies', 'stringing_pearls', 'rolling_and_filling_dough', 'assembling_candy_bouquets', 'pressing_leaves', 'assembling_toy_parts', 'lasting_shoes', 'wiring_electrical_plugs', 'packing_crackers', 'measuring_flour', 'organizing_desks', 'rolling_croissants', 'cutting_sushi_rolls', 'opening_boxes', 'coating_eggs', 'washing_seedlings', 'crocheting_yarn', 'drying_plates', 'packing_shirts', 'crafting_paper_rolls', 'reassembling_laptops', 'bagging_ingredients', 'shaving_meat', 'packaging_beverage_portions', 'packing_rice_bags', 'assembling_metal_frames', 'sealing_ribbon_petals', 'bagging_forks', 'wrapping_twine', 'cleaning_grocery_items', 'examining_trinkets', 'packaging_pastries', 'cleaning_fan_grills', 'making_croissants', 'forming_flower_petals', 'singeing_petals', 'cutting_cables', 'dusting_papers', 'rinsing_kitchen_utensils', 'layering_colored_papers', 'listing_store_items', 'adding_toppings', 'shaping_chocolate_balls', 'processing_customer_orders', 'peeling_adhesive_strips', 'assembling_balloons', 'labeling_pens', 'folding_shopping_bags', 'packaging_fish_food', 'straining_tea', 'shaping_plastic_petals', 'conditioning_clothes', 'storing_groceries', 'packaging_garments', 'trimming_wood_veneer', 'packaging_liquid_foods', 'cleaning_objects', 'tying_chair_sashes', 'washing_mop_heads', 'separating_fabrics', 'assembling_bag_handles', 'counting_banknotes', 'assembling_electrical_parts', 'preparing_soils', 'peeling_spices', 'welding_metal_grates', 'trimming_wood_planks', 'cutting_foam_leaves', 'repairing_mobiles', 'testing_touch_screen', 'filling_wooden_gaps', 'transferring_toppings', 'packaging_croissants', 'bagging_peas', 'tying_plastic_on_branches', 'weighing_beans', 'unscrewing_electronics', 'packaging_cardboard', 'drawing_lines', 'sorting_utensils', 'dusting_chairs', 'packing_watch_parts', 'stirring_noodles', 'snipping_dough', 'piping_doughs', 'inspecting_lcd_panels', 'cutting_backpacks', 'crafting_paper_decorations', 'bottling_liquids', 'preparing_crepe_skins', 'guiding_plastic_films', 'cleaning_refrigerator_bins', 'slicing_bitter_melons', 'flipping_pages', 'cutting_plastic_bags', 'harvesting_chilies', 'shaping_dough_pastries', 'cleaning_cases', 'applying_tape_to_decorations', 'decorating_caps', 'making_popcorn', 'waxing_clothes', 'sorting_noodles', 'trimming_food_items', 'opening_plastic_bags', 'sorting_spice_containers', 'washing_metal_plates', 'transferring_tomatoes', 'tagging_shoes', 'cleaning_and_piping', 'assembling_axes', 'refining_bouquets', 'cleaning_booklets', 'packaging_desserts', 'fitting_foam_components', 'bending_metal', 'measuring_strings', 'opening_power_supplies', 'organizing_medicine', 'measuring_frames', 'kneading_fondant', 'emptying_packets', 'cutting_tags_off_socks', 'preparing_coffee_beans', 'tagging_flowers_on_clothing', 'cooking_cakes', 'organizing_forks', 'stapling_cake_containers', 'securing_components', 'unpicking_clothes', 'shaping_clay', 'repairing_jackets', 'saucing_pizzas', 'loosening_bottom_brackets', 'handling_paper_strips', 'digging_soil', 'tagging_goods', 'inflating_balloons', 'cleaning_squids', 'rolling_fabric_petals', 'making_pies', 'washing_frying_pan', 'folding_ribbons', 'refining_wax_flakes', 'cleaning_grills', 'washing_shoes', 'filling_plastic_bag', 'washing_cables', 'transferring_vegetables', 'applying_oil', 'preparing_chocolate_sticks', 'cleaning_jukeboxes', 'processing_sachets', 'prepping_fruits', 'organizing_plates_and_bowls', 'cutting_fried_foods', 'packing_polishing_pads', 'collecting_rings', 'installing_guitar_strings', 'packing_stationery', 'coating_molds', 'shaping_hats', 'cleaning_watch_components', 'packaging_cups', 'cleaning_screens', 'operating_washing_machine', 'filling_chocolate_molds', 'sanitizing_meat_slicers', 'crafting_headdresses', 'applying_stickers', 'measuring_seeds', 'wiping_desks', 'making_lattes', 'cooking_popcorn', 'removing_stickers', 'assembling_invitations', 'peeling_lettuce', 'mixing_perfumes', 'using_drill_press', 'repairing_televisions', 'muddling_strawberries', 'painting_cages', 'polishing_silverware', 'arranging_miniature_gardens', 'processing_jackfruits', 'packaging_pastes', 'preparing_fried_chicken', 'applying_solution_to_sneakers', 'assembling_sculptures', 'assembling_ribbon_layers', 'wiping_fittings', 'sorting_fishing_supplies', 'processing_laundry', 'cleaning_packaging', 'filling_gift_boxes', 'cleaning_meat_slicer', 'sorting_paper_slips', 'cleaning_plants', 'rolling_paper_tubes', 'stirring_paint', 'shaping_cardboard_bases', 'crushing_lemongrass', 'mixing_beverages', 'packaging_baked_goods', 'gluing_buds', 'shaping_dough_rings', 'dusting_items', 'polishing_sculptures', 'sewing_stuffed_animals', 'breaking_chilies', 'hanging_accessories', 'cutting_cardboard_shapes', 'servicing_locks', 'wiping_books', 'grinding_motorcycle_frames', 'writing_on_notepad', 'weighing_dough_portions', 'folding_liners', 'skewering_ingredients', 'tracing_circuits', 'cutting_ham', 'tidying_toys', 'comparing_components', 'sorting_strips', 'stapling_decorations', 'sewing_shoe_soles', 'preparing_seasonings', 'making_tags', 'wiping_workbench', 'sorting_souvenirs', 'packing_spools', 'bagging_pizza_bases', 'cutting_tape', 'organizing_cleaning_items', 'preparing_turnovers', 'washing_motorcycles', 'adding_beads', 'cutting_film', 'decorating_pastries', 'folding_paper_wrappers', 'prepping_greens', 'cleaning_boots', 'cleaning_and_arranging_boxes', 'filling_bins', 'handling_printed_sheets', 'making_dough_pockets', 'modifying_harnesses', 'preparing_takeout', 'packing_bags', 'packing_trims', 'marking_foam_pieces', 'arranging_nail_tips', 'storing_eggs', 'unpacking_food_items', 'assembling_headdresses', 'reassembling_pumps', 'cleaning_and_shelving_books', 'cleaning_printer_components', 'mixing_cheese', 'sorting_snails', 'packing_craft_items', 'sanding_plastic_housings', 'filtering_liquid', 'rolling_up_plastic_mulch', 'marking_paper_strips', 'shaving_wood', 'bagging_pellets', 'preparing_food_packets', 'folding_packaging_paper', 'cleaning_batteries', 'cleaning_clothes_rack', 'preparing_base_materials', 'arranging_placemats', 'mixing_powder', 'bagging_coffee', 'wrapping_small_items', 'cleaning_tables', 'printing_clothes', 'filling_sauce_tubes', 'packing_seeds', 'packing_backpack', 'pinning_pillows', 'cleaning_prep_area', 'portioning_snacks', 'stacking_plates', 'adding_foliage', 'cleaning_pantry_items', 'cleaning_watch_parts', 'cutting_yarn', 'clearing_debris', 'assembling_fabric_roses', 'straining_snacks', 'cleaning_motor_parts', 'cleaning_fixtures', 'trimming_hedges', 'assembling_gift_pouches', 'adding_decorations', 'sorting_cash', 'trimming_booklets', 'removing_stems_from_leaves', 'scrubbing_motherboards', 'machining_metals', 'shaping_snacks', 'wrapping_meat', 'restocking_refrigerators', 'measuring_coffee_powder', 'adjusting_shoelaces', 'processing_sticks', 'frying_cassava_slices', 'soldering_circuits', 'positioning_ribbon', 'placing_stickers', 'separating_seedlings', 'sewing_covers', 'shaping_yarn_flowers', 'wiring_motorcycles', 'cleaning_birds_nests', 'labeling_strings', 'unscrewing_fans', 'assembling_connectors', 'sorting_candies', 'sorting_cloves', 'dyeing_leather', 'wrapping_napkins', 'stretching_balloons', 'preparing_bowls', 'cleaning_straws', 'wiping_table', 'bottling_liquid', 'folding_cardboard_box', 'preparing_food_mixture', 'sanding_wooden_parts', 'grinding_chilies', 'wrapping_bags', 'packaging_coffee_grounds', 'blending_mixture', 'grinding_parts', 'wrapping_wooden_spoons', 'fluffing_pillows', 'arranging_wooden_strips', 'folding_fans', 'packing_orders', 'washing_scooters', 'stacking_dough_sheets', 'tightening_gear_bolts', 'sorting_popcorn', 'taping_cards', 'refining_chocolate', 'cleaning_cupping_sets', 'assembling_yarn_flowers', 'repairing_laptops', 'cutting_chili_peppers', 'decorating_tray', 'finalizing_bouquets', 'gluing_foams', 'cleaning_fish', 'prepping_cake_batter', 'layering_desserts', 'organizing_cups', 'cutting_leathers', 'layering_cakes', 'grilling_meat', 'cutting_fondant_letters', 'baking_cookies', 'peeling_spring_onions', 'preparing_frying_oil', 'arranging_chocolate_bars', 'organizing_notebook', 'assembling_wood_mosaics', 'pouring_and_spreading_batter', 'arranging_pine_branches', 'connecting_circuitry', 'assembling_decorations', 'skewering_hot_dogs', 'forming_cookies', 'stitching_shoe_insoles', 'filling_tank', 'hanging_pants', 'packaging_food_items', 'preparing_floral_sticks', 'cleaning_air_fryers', 'adjusting_clothes', 'assembling_fabric_flowers', 'placing_items', 'securing_items', 'adjusting_shoes', 'making_lumpia', 'sorting_plastic', 'cooking_breads', 'decorating_branches', 'gluing_screens', 'disassembling_clocks', 'packaging_lemons', 'tying_ribbons_clothes', 'organizing_underwear', 'mounting_speakers', 'layering_candy_bars', 'scrubbing_toys', 'shoveling_compost', 'marking_packages', 'organizing_bamboo_sticks', 'slicing_ingredients', 'unwinding_thread', 'tying_leaves', 'grating_cheese', 'preparing_decorative_paper', 'plastering_molds', 'cooking_street_food', 'picking_weeds', 'assembling_tacos', 'hand_sewing', 'shaping_fillings', 'cleaning_stove_surface', 'winding_cables', 'packing_food_strips', 'lidding_cups', 'packaging_fringe_strips', 'packaging_boxes', 'spraying_plants', 'bagging_meatballs', 'cleaning_papayas', 'scraping_residue', 'molding_chocolates', 'wrapping_cakes', 'placing_pebbles', 'organizing_cardboard', 'stuffing_peppers', 'sewing_insoles', 'gluing_wooden_sticks', 'chopping_potatoes', 'pouring_coffee', 'rolling_chocolate_balls', 'rolling_cones', 'applying_leather_finish', 'washing_food_items', 'preparing_arrangements', 'testing_tablets', 'cutting_peaches', 'repairing_rods', 'gluing_strings', 'planting_stalks', 'weighing_goods', 'sewing_ribbon_bows', 'cleaning_pastry_trays', 'stacking_folders', 'bundling_underwear', 'cleaning_rice_cookers', 'assembling_mousepads', 'organizing_cabinet', 'assembling_wooden_structures', 'punching_metal', 'mincing_carrots', 'cutting_patterns', 'practicing_rhythms', 'cutting_plastic_wrappers', 'shaping_dough_strands', 'coating_snacks', 'organizing_floral_stems', 'sorting_tags', 'organizing_fabric_strips', 'crafting_flower_components', 'wrapping_green_beans', 'inserting_stems', 'processing_plants', 'assembling_favors', 'positioning_wooden_boards', 'organizing_objects', 'stitching_shoes', 'cutting_wires', 'layering_stems', 'finishing_wood_pieces', 'forming_meatballs', 'prying_bezels', 'packing_bras', 'portioning_flour', 'molding_food', 'reassembling_heating_elements', 'rinsing_containers', 'cutting_photo_sheets', 'fitting_dental_pieces', 'adding_flower_stems', 'securing_hinges', 'unpacking_packages', 'preparing_baking_trays', 'handling_meat', 'packing_face_masks', 'preparing_tapes', 'machining_parts', 'repairing_iron', 'packing_keychains', 'preparing_egg_cartons', 'adjusting_fishing_rod_guides', 'dusting_table', 'trimming_veneer', 'preparing_filler', 'soldering_connections', 'preparing_food_trays', 'painting_patterns', 'preparing_sausages', 'securing_styrofoam', 'securing_screws', 'marking_metal_pieces', 'wrapping_meat_portions', 'unloading_fridge', 'weaving_lampshades', 'taping_planks', 'sorting_macaroni', 'finalizing_financial_records', 'measuring_coffee_grounds', 'organizing_spoons', 'drying_glasses', 'unloading_mugs', 'packaging_small_items', 'arranging_toys', 'assembling_cars', 'packaging_shredded_paper', 'crushing_ingredients', 'filling_and_sealing_empanadas', 'brushing_bags', 'mixing_pasta', 'slicing_squid', 'shaping_wood', 'unloading_glasses', 'chopping_fish', 'covering_notebooks', 'cutting_pants', 'sifting_powders', 'washing_shoelaces', 'smoothing_leaves', 'weighing_peppers', 'preparing_onions', 'screwing_hard_drives', 'mixing_animal_feed', 'trimming_notebooks', 'preparing_wire_coils', 'polishing_leather_bag', 'packaging_gift_items', 'skewering_snacks', 'wrapping_fruit_trays', 'shaving_sugar', 'cleaning_internal_components', 'marking_wood', 'shaping_plastics', 'unpacking_shoe_soles', 'cleaning_projectors', 'assembling_dough_roses', 'attaching_candies', 'making_matcha_drinks', 'planting_ferns', 'filling_planter_bags', 'scrubbing_wheels', 'gluing_plastic_pieces', 'making_soil_balls', 'sifting_garlic', 'folding_roses', 'mixing_chocolate', 'taking_out_trash', 'installing_cpus', 'folding_and_gluing_bags', 'making_carrots', 'cleaning_shelf_board', 'arranging_doughs', 'grinding_metal_pieces', 'organizing_crockery', 'cutting_pill_blisters', 'smoothing_foam_edges', 'organizing_artificial_plants', 'portioning_dessert', 'arranging_dried_grass', 'cleaning_windowsills', 'trimming_boards', 'disassembling_brake_master_cylinders', 'attaching_labels', 'bagging_pastries', 'folding_crepe_paper', 'unscrewing_internal_components', 'measuring_wires', 'boxing_towels', 'adding_powder_to_bags', 'mixing_soils', 'fertilizing_crops', 'filling_potting_bags', 'assembling_flowers', 'filling_sandwiches', 'portioning_batter', 'smoothing_cake_frosting', 'connecting_flex_cables', 'unloading_refrigerators', 'bookbinding', 'labeling_sunglasses', 'covering_chairs', 'sanding_wooden_pieces', 'organizing_packaged_clothes', 'inspecting_paint', 'spreading_sauce', 'drying_molds', 'cleaning_intestines', 'organizing_tissues', 'inspecting_buns', 'removing_belt_loops', 'assembling_models', 'organizing_utensils', 'categorizing_items', 'prying_phone_components', 'sanding_material', 'scraping_paints', 'cutting_metal', 'blending_sauce', 'folding_pastry_box', 'adding_soil_to_containers', 'placing_bottles', 'haircutting', 'unhanging_clothes', 'applying_veneer_tape', 'refilling_ink_cartridges', 'preparing_floral_components', 'polishing_table_rails', 'cleaning_sachets', 'arranging_keychains', 'assembling_gift_arrangements', 'inserting_wire_bindings', 'packaging_tart_shells', 'cutting_buns', 'marking_foam_boards', 'rolling_out_dough', 'cleaning_mat', 'prying_battery_casings', 'repairing_fabric', 'reassembling_keyboards', 'organizing_desk_items', 'bundling_grass', 'assembling_sushi_rolls', 'disassembling_optical_drives', 'cutting_wooden_blocks', 'mixing_food_items', 'removing_phone_covers', 'painting_sneakers', 'plating_rice', 'packaging_powder_portions', 'tying_stri', 'cleaning_planters', 'flattening_bread_slices', 'detailing_leaves', 'stapling_plastic_bags', 'cutting_noodles', 'labeling_and_boxing', 'rolling_banknotes', 'unwrapping_food', 'arranging_objects', 'seasoning_salad', 'removing_screws', 'smoothing_bed_sheets', 'cleaning_mobile_phones', 'inspecting_parts', 'peeling_vegetables', 'organizing_sticks', 'labeling_watch_parts', 'collecting_laundry', 'sewing_fabric_pieces', 'polishing_tableware', 'packing_creamer_powder', 'storing_packaging', 'packing_food_bags', 'cleaning_fabrics', 'arranging_blankets', 'dicing_sausages', 'assembling_felt_flowers', 'assembling_syringes', 'sorting_bamboo_strips', 'filing_silver_pieces', 'folding_fabric_strips', 'adding_fruit_to_bowls', 'arranging_pastries', 'adjusting_chains', 'punching_cardboards', 'removing_screen_bezels', 'shaping_dental_mold', 'planting_leaf_cuttings', 'punching_cardboard', 'rolling_paper_strips', 'rolling_pancakes', 'preparing_flavored_coffee', 'bagging_grocery_items', 'arranging_coffee', 'preparing_laser_cutter', 'organizing_wires', 'packing_nails', 'forming_dough_rings', 'installing_grommets', 'stripping_furniture', 'repairing_outlets', 'frying_fritters', 'removing_donuts', 'folding_cards', 'organizing_batteries', 'harvesting_chili_peppers', 'compressing_cushions', 'packing_fried_foods', 'stirring_drinks', 'organizing_folded_clothes', 'filling_terrarium', 'capping_sauce_cups', 'soldering_metal_pieces', 'cooking_chicken', 'inspecting_floral_stems', 'assembling_foam_components', 'weighing_nails', 'brushing_motorcycle_parts', 'cleaning_cutlery_trays', 'peeling_lemons', 'rinsing_floor', 'making_beaded_keychains', 'bundling_palm_leaf_ribs', 'packaging_soup', 'cleaning_glass_cups', 'wrapping_chair_legs', 'frying_pastry_noodles', 'packaging_nachos', 'assembling_keycaps', 'bagging_fabrics', 'seasoning_stews', 'making_rice_papers', 'preparing_siomai', 'rinsing_machine_components', 'coloring_doughs', 'packaging_peas', 'assembling_floral_patterns', 'scooping_snacks', 'cleaning_baking_trays', 'reassembling_smartphones', 'organizing_kitchen_counter', 'cutting_vegetables', 'frying_buns', 'sewing_sneakers', 'crafting_ribbon_flowers', 'preparing_planting_containers', 'packaging_flowers', 'cleaning_pants', 'making_decorative_bows', 'sorting_food_slices', 'gluing_lenses', 'folding_hat_edges', 'weighing_potatoes', 'cleaning_onions', 'arranging_glasses', 'writing_in_notebooks', 'removing_printer_components', 'wiping_bottles', 'pouring_chocolate', 'forming_rose_heads', 'sealing_cords', 'taping_flowers', 'mincing_meat', 'pouring_beverage', 'chopping_mushrooms', 'writing_labels', 'refining_floral_trees', 'tightening_screws', 'applying_glue_to_cards', 'watering_lawn', 'securing_furniture', 'unscrewing_casings', 'splitting_fibers', 'packaging_coffee_powders', 'packing_guavas', 'organizing_pipe_cleaners', 'cutting_out_logos', 'preparing_food_ingredients', 'washing_bins', 'cleaning_cabinets', 'repairing_chairs', 'tidying_kitchen', 'organizing_refrigerator', 'wrapping_forks', 'wrapping_rods', 'organizing_swabs', 'trimming_sheets', 'securing_gpus', 'sewing_fabrics', 'cutting_model_parts', 'preparing_chicken_fingers', 'brushing_cages', 'wrapping_floral_foam', 'gluing_shoe_insoles', 'bagging_muffins', 'frying_tofu', 'inspecting_clothes', 'lidding_bowls', 'pruning_plants', 'packaging_coffee_powder', 'dusting_book_pages', 'preparing_money', 'folding_bedding', 'adjusting_petals', 'cutting_soles', 'threading_cables', 'mixing_pastes', 'bundling_rubber_bands', 'fitting_strips', '

In [15]:
# Flagship Fold Clothes Data
df[df["task"] == "washing_coffee_equipment"]

,episode_hash,operator,task,embodiment,robot_name,num_frames,task_description,scene,objects,zarr_processed_path,zarr_mp4_path,zarr_processing_error,is_deleted,data_type
38706,69b4bb5bedfc296664603866,6948becb5c0479a0fb82ef1a,washing_coffee_equipment,mecka,mecka_bimanual,2545,A person meticulously cleans and manipulates a...,dishwashing_area,"[""portafilter_basket"", ""shower_screen"", ""sink""...",/vol/zarr_output/69b4bb5bedfc296664603866.zarr,,,False,flagship