In [5]:
from sqlalchemy import (
    Boolean,
    Column,
    Float,
    Integer,
    MetaData,
    String,
    Table,
    text,
    update,
)

from egomimic.utils.aws.aws_sql import (
    TableRow,
    create_default_engine,
    episode_table_to_df,
)

In [6]:
engine = create_default_engine()

Tables in schema 'app': ['episodes']

In [7]:
df = episode_table_to_df(engine)
df

,episode_hash,operator,task,embodiment,robot_name,num_frames,task_description,scene,objects,zarr_processed_path,zarr_mp4_path,zarr_processing_error,is_deleted,data_type
0,69c2e11d8d047e12c1437b49,696a41576adfd3c664a4884d,wrapping_bouquets,mecka,mecka_bimanual,3599,A person is meticulously assembling a decorati...,design_station,"[""rose_bouquet"", ""wrapping_paper"", ""tape"", ""sc...",/vol/zarr_output/69c2e11d8d047e12c1437b49.zarr,,,False,flagship
1,692ba7636f03b95efa014e19,691fb9aabe785d95f3c92975,sorting_coffee_beans,mecka,mecka_bimanual,2701,The person is sorting coffee beans on a wooden...,coffee_processing_area,"[""coffee_beans"", ""wooden_tray"", ""bowl"", ""stool""]",/vol/egoverse-zarr-data/692ba7636f03b95efa014e...,/vol/egoverse-zarr-data/692ba7636f03b95efa014e...,,False,flagship
2,69c2e11ed5c62ba7c4d5abd0,696875ceb5a168dd96784e60,portioning_dough,mecka,mecka_bimanual,3595,A person uses a tool to cut green dough into s...,production_area,"[""dough"", ""scale"", ""baking_tray""]",/vol/zarr_output/69c2e11ed5c62ba7c4d5abd0.zarr,,,False,flagship
3,693ceb7686fa42a6428d031d,6939a1c4c67c9e4814b02dbd,packaging_products,mecka,mecka_bimanual,2701,The person is sorting and inspecting various f...,stockroom,"[""face_masks"", ""plastic_bags"", ""cardboard_box""]",/vol/egoverse-zarr-data/693ceb7686fa42a6428d03...,/vol/egoverse-zarr-data/693ceb7686fa42a6428d03...,,False,flagship
4,69c2e120f2e7c4de1485053b,696722f683a9fdf2d86f263b,grinding_coffee_beans,mecka,mecka_bimanual,3599,The person is preparing a manual coffee grinde...,counter,"[""coffee_beans"", ""ground_coffee"", ""coffee_bags...",/vol/zarr_output/69c2e120f2e7c4de1485053b.zarr,,,False,flagship
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200095,69c43971286a122e71af6145,6969246e567cdf8c8737861a,peeling_garlic,mecka,mecka_bimanual,2095,A person is manually peeling garlic bulbs by h...,produce_section,"[""garlic"", ""mesh_bags"", ""garlic_skins""]",/vol/zarr_output/69c43971286a122e71af6145.zarr,,,False,flagship
200096,69c4397268912ffee1187965,696ef6184766dbef4c55d59c,ironing_clothes,mecka,mecka_bimanual,2095,The person is ironing and folding a black garm...,stockroom,"[""t_shirt"", ""ironing_pad"", ""folded_clothes""]",/vol/zarr_output/69c4397268912ffee1187965.zarr,,,False,flagship
200097,69c43974354a8e82ba8b68f3,69462b145f30bef91a6668e4,cutting_meat,mecka,mecka_bimanual,2065,A person is slicing a large piece of meat into...,kitchen,"[""raw_meat"", ""bowl"", ""cutting_board""]",/vol/zarr_output/69c43974354a8e82ba8b68f3.zarr,,,False,flagship
200098,69c4397d75aab850dc99dc8d,6981e6b9f8ca4464d98d2f77,kneading_dough,mecka,mecka_bimanual,2056,prepare green dough by mixing liquid ingredien...,production_area,"[""dough"", ""bowl"", ""liquid_container"", ""flour_b...",/vol/zarr_output/69c4397d75aab850dc99dc8d.zarr,,,False,flagship
200099,69c4398020e5477dc5e7c333,69738b3189fa4bc311d05ec4,labeling_pastries,mecka,mecka_bimanual,1945,The person is going through a tray of plastic-...,production_area,"[""pastries"", ""labels"", ""tray"", ""plastic_bags"",...",/vol/zarr_output/69c4398020e5477dc5e7c333.zarr,,,False,flagship

In [9]:
# Filter to certain lab
df[df["zarr_processed_path"] == ""]

,episode_hash,operator,task,embodiment,robot_name,num_frames,task_description,scene,objects,zarr_processed_path,zarr_mp4_path,zarr_processing_error,is_deleted,data_type
94,69bb084cf7dd56e062995ca9,69ae7b50d22d996552543839,dishwashing,mecka,mecka_bimanual,3595,A person is washing various dishes including b...,kitchen,"[""plates"", ""bowls"", ""pot_lids"", ""sponge"", ""dis...",,,zarr not found in volume at /vol/zarr_output/6...,False,flagship
236,69c2e1ecd8e20858bef42e8d,691bd64365e285b6ff78e146,folding_sleeping_bags,mecka,mecka_bimanual,3595,A person packs an object into a stuff sack and...,storage_room,"[""sleeping_bag"", ""compression_sack"", ""camping_...",,,zarr not found in volume at /vol/zarr_output/6...,False,flagship
554,69c53b3975aabe361771fd7f,69684f29b5a168dd9677e4f0,preparing_food,mecka,mecka_bimanual,2698,The person is carefully placing red fish roe o...,table_section,"[""fish_pieces"", ""fish_roe"", ""containers"", ""pla...",,,zarr not found in volume at /vol/zarr_output/6...,False,flagship
618,69bdd0302cbbe1cb9c01fada,696eed484766dbef4c55c519,packaging_clothes,mecka,mecka_bimanual,2728,A person packages a folded shirt into a plasti...,folding_station,"[""shirt"", ""plastic_bag"", ""sticky_notes"", ""pen""...",,,zarr not found in volume at /vol/zarr_output/6...,False,flagship
688,69c541d9d43546f51830e7cc,68fee2f8736a3838bdb9716e,preparing_dough,mecka,mecka_bimanual,3265,A person is cutting a long roll of dough into ...,production_area,"[""dough"", ""baking_tray"", ""knife""]",,,zarr not found in volume at /vol/zarr_output/6...,False,flagship
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199709,69c4377198c23ab2e18f17f8,69309e8a6cc68212bd07b94e,peeling_carrots,mecka,mecka_bimanual,2095,A person prepares a carrot by peeling its skin...,kitchen,"[""carrots"", ""trash_bin"", ""prep_table""]",,,zarr not found in volume at /vol/zarr_output/6...,False,flagship
199767,69bb8ac807f3a0026d3d4938,6989b042f8ca4464d99e7e9b,cooking,mecka,mecka_bimanual,2414,A person is preparing soup by adding a packet ...,kitchen,"[""soup_mix_packet"", ""spice_jars"", ""pot"", ""wrap...",,,zarr not found in volume at /vol/zarr_output/6...,False,flagship
199829,69b9afae6559e3976eeeeee6,6989541df8ca4464d99df19e,dishwashing,mecka,mecka_bimanual,3445,"The person is washing dishes in a sink, specif...",kitchen,"[""wok"", ""bowl"", ""sponge"", ""spatula"", ""faucet""]",,,zarr not found in volume at /vol/zarr_output/6...,False,flagship
199944,69cc2eac956dc1eb03b66df0,696db0da4766dbef4c50cd4b,portioning_food,mecka,mecka_bimanual,2755,A person is portioning cooked meat and vegetab...,prep_area,"[""meat"", ""vegetables"", ""plastic_bags"", ""metal_...",,,zarr not found in volume at /vol/zarr_output/6...,False,flagship
199969,69c438b820e5477dc5e7c327,697e5f50b4c71311babe4a04,preparing_empanadas,mecka,mecka_bimanual,2095,The person is preparing stuffed dough dumpling...,pizza_prep_station,"[""dough"", ""ham"", ""cheese"", ""containers"", ""pizz...",,,zarr not found in volume at /vol/zarr_output/6...,False,flagship

In [ ]:
# Flagship Fold Clothes Data
df[(df["task"] == "fold_clothes") & df["lab"].isin(["rl2", "eth", "song", "wang"])]